# DonutDisablePhantom configuration

# Worlds where the /phantom command is not allowed
blacklist-world:
  - world_nether
  - world_the_end

# Maximum range (in blocks) to check for nearby players who disabled phantoms
Max-Range: 48

messages:
  chat: true
  not_allowed_world: "&cYou cannot use this command in this world."
  enable: "&aPhantoms disabled for you."
  disable: "&cPhantoms enabled for you."
  enable-sound: "UI_TOAST_CHALLENGE_COMPLETE"
  disable-sound: "BLOCK_NOTE_BLOCK_PLING"

# Database settings
database:
  # sqlite or mysql
  type: sqlite

  sqlite:
    # File name stored in the plugin's data folder
    file: "disable-phantom.db"

  mysql:
    host: "localhost"
    port: 3306
    database: "minecraft"
    username: "root"
    password: ""