name: DonutDisablePhantom
main: macronis.xdisablephantom.DisablePhantomPlugin
version: ${project.version}
api-version: '1.21'
author: Macronis
description: Toggle phantom spawning per-player
commands:
  phantom:
    description: Toggle phantom spawns around you
    usage: /phantom
    permission: donutdisablephantom.use
  donutdisablephantom:
    description: Plugin admin command
    usage: /donutdisablephantom reload
    permission: donutdisablephantom.admin
permissions:
  donutdisablephantom.use:
    default: true
  donutdisablephantom.admin:
    default: op